/**
 * 该文件是为了按需加载，剔除掉了一些不需要的框架组件。
 * 减少了编译支持库包大小
 * @author matthew.mak
 * 当需要更多组件依赖时，在该文件加入即可
 */
import {
  ConfigProvider,
  Layout,
  Input,
  InputNumber,
  Button,
  Switch,
  Radio,
  Checkbox,
  Select,
  Card,
  Form,
  Row,
  Col,
  Modal,
  Table,
  Tabs,
  Badge,
  Popover,
  Dropdown,
  List,
  Avatar,
  Breadcrumb,
  Steps,
  Spin,
  Menu,
  Drawer,
  Tooltip,
  Alert,
  Tag,
  Divider,
  DatePicker,
  TimePicker,
  Upload,
  Progress,
  Skeleton,
  Popconfirm,
  message,
  notification,
  TreeSelect,
  Tree,
  Transfer,
  Empty,
  PageHeader,
  Descriptions,
  Result,
  Collapse
} from 'ant-design-vue'

// 导入 Ant Design 图标库
import {
  UserOutlined,
  LockOutlined,
  SettingOutlined,
  HomeOutlined,
  DashboardOutlined,
  BellOutlined,
  QuestionCircleOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  GlobalOutlined,
  SearchOutlined,
  PlusOutlined,
  DeleteOutlined,
  EditOutlined,
  ExclamationCircleOutlined,
  CheckOutlined,
  CloseOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  ReloadOutlined,
  ColumnHeightOutlined,
  FullscreenOutlined,
  AppstoreOutlined,
  TeamOutlined,
  FileDoneOutlined,
  MailOutlined,
  FileOutlined,
  FolderOutlined,
  IdcardOutlined,
  LogoutOutlined
} from '@ant-design/icons-vue'

// 导出组件供Vue 3应用使用
export const components = [
  ConfigProvider,
  Layout,
  Input,
  InputNumber,
  Button,
  Switch,
  Radio,
  Checkbox,
  Select,
  Card,
  Form,
  Row,
  Col,
  Modal,
  Table,
  Tabs,
  Badge,
  Popover,
  Dropdown,
  List,
  Avatar,
  Breadcrumb,
  Steps,
  Spin,
  Menu,
  Drawer,
  Tooltip,
  Alert,
  Tag,
  Divider,
  DatePicker,
  TimePicker,
  Upload,
  Progress,
  Skeleton,
  Popconfirm,
  Collapse,
  TreeSelect,
  Tree,
  Transfer,
  Empty,
  PageHeader,
  Descriptions,
  Result
]

// 导出图标组件
export const icons = {
  UserOutlined,
  LockOutlined,
  SettingOutlined,
  HomeOutlined,
  DashboardOutlined,
  BellOutlined,
  QuestionCircleOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  GlobalOutlined,
  SearchOutlined,
  PlusOutlined,
  DeleteOutlined,
  EditOutlined,
  ExclamationCircleOutlined,
  CheckOutlined,
  CloseOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  ReloadOutlined,
  ColumnHeightOutlined,
  FullscreenOutlined,
  AppstoreOutlined,
  TeamOutlined,
  FileDoneOutlined,
  MailOutlined,
  FileOutlined,
  FolderOutlined,
  IdcardOutlined,
  LogoutOutlined
}

// 导出全局属性
export const globalProperties = {
  $confirm: Modal.confirm,
  $message: message,
  $notification: notification,
  $info: Modal.info,
  $success: Modal.success,
  $error: Modal.error,
  $warning: Modal.warning
}
